export type SeedQuestion = {
  slug: string;
  prompt: string;
  mode: 'behavioral' | 'technical' | 'system_design' | 'company_pack';
  pack: string;
  difficulty: number;
  tags: string[];
  competencies: string[];
  timeLimitSec: number;
};

export const seedQuestions: SeedQuestion[] = [
  {
    slug: 'challenge-star',
    prompt: 'Tell me about a challenge you faced and how you handled it.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['challenge', 'ownership'],
    competencies: ['ownership', 'problem_solving'],
    timeLimitSec: 120,
  },
  {
    slug: 'conflict',
    prompt: 'Describe a time you had a conflict on a team. What did you do?',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['collaboration', 'communication'],
    competencies: ['teamwork', 'communication'],
    timeLimitSec: 120,
  },
  {
    slug: 'impact',
    prompt: 'What is a project you’re proud of? What was the impact?',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['impact', 'results'],
    competencies: ['impact', 'results'],
    timeLimitSec: 120,
  },
  {
    slug: 'failure',
    prompt: 'Tell me about a failure and what you learned.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['learning', 'growth'],
    competencies: ['learning', 'resilience'],
    timeLimitSec: 120,
  },
  {
    slug: 'leadership-initiative',
    prompt: 'Describe a time you took initiative on a project without being asked.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 2,
    tags: ['initiative', 'ownership'],
    competencies: ['ownership', 'bias_for_action'],
    timeLimitSec: 120,
  },
  {
    slug: 'prioritization-tradeoffs',
    prompt: 'Tell me about a time you had to prioritize competing tasks.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['prioritization', 'planning'],
    competencies: ['prioritization', 'time_management'],
    timeLimitSec: 120,
  },
  {
    slug: 'ambiguity',
    prompt: 'Describe a time you worked with ambiguous requirements.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['ambiguity', 'clarity'],
    competencies: ['clarifying', 'problem_solving'],
    timeLimitSec: 120,
  },
  {
    slug: 'feedback-received',
    prompt: 'Tell me about feedback you received and how you acted on it.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 2,
    tags: ['feedback', 'growth'],
    competencies: ['coachability', 'learning'],
    timeLimitSec: 120,
  },
  {
    slug: 'feedback-given',
    prompt: 'Describe a time you gave constructive feedback.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['communication', 'leadership'],
    competencies: ['communication', 'leadership'],
    timeLimitSec: 120,
  },
  {
    slug: 'stakeholder-management',
    prompt: 'Describe a time you managed a difficult stakeholder.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 4,
    tags: ['stakeholders', 'influence'],
    competencies: ['influence', 'communication'],
    timeLimitSec: 150,
  },
  {
    slug: 'customer-obsession',
    prompt: 'Tell me about a time you advocated for the user or customer.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 2,
    tags: ['customer', 'empathy'],
    competencies: ['customer_focus', 'empathy'],
    timeLimitSec: 120,
  },
  {
    slug: 'mistake-recovery',
    prompt: 'Describe a mistake you made and how you recovered.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['accountability', 'resilience'],
    competencies: ['accountability', 'resilience'],
    timeLimitSec: 120,
  },
  {
    slug: 'conflicting-priorities',
    prompt: 'Tell me about a time you balanced quality with a tight deadline.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['deadline', 'tradeoffs'],
    competencies: ['prioritization', 'delivery'],
    timeLimitSec: 120,
  },
  {
    slug: 'mentorship',
    prompt: 'Describe a time you mentored or helped a teammate.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 2,
    tags: ['mentorship', 'teamwork'],
    competencies: ['teamwork', 'leadership'],
    timeLimitSec: 120,
  },
  {
    slug: 'cross-functional',
    prompt: 'Tell me about a time you worked cross-functionally to deliver a project.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['cross-functional', 'collaboration'],
    competencies: ['collaboration', 'communication'],
    timeLimitSec: 120,
  },
  {
    slug: 'influence-without-authority',
    prompt: 'Describe a time you influenced a decision without formal authority.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 4,
    tags: ['influence', 'leadership'],
    competencies: ['influence', 'leadership'],
    timeLimitSec: 150,
  },
  {
    slug: 'ownership-long-term',
    prompt: 'Tell me about a time you took ownership of a long-term problem.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 4,
    tags: ['ownership', 'persistence'],
    competencies: ['ownership', 'execution'],
    timeLimitSec: 150,
  },
  {
    slug: 'learn-new-tech',
    prompt: 'Describe a time you had to learn a new tool or technology quickly.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 2,
    tags: ['learning', 'adaptability'],
    competencies: ['learning', 'adaptability'],
    timeLimitSec: 120,
  },
  {
    slug: 'quality-improvement',
    prompt: 'Tell me about a time you improved the quality or reliability of a system.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['quality', 'reliability'],
    competencies: ['quality', 'problem_solving'],
    timeLimitSec: 150,
  },
  {
    slug: 'data-driven',
    prompt: 'Describe a time you used data to make a decision.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['data', 'decision'],
    competencies: ['data_analysis', 'decision_making'],
    timeLimitSec: 120,
  },
  {
    slug: 'scope-change',
    prompt: 'Tell me about a time scope changed late in a project.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['scope', 'change'],
    competencies: ['adaptability', 'communication'],
    timeLimitSec: 120,
  },
  {
    slug: 'process-improvement',
    prompt: 'Describe a process you improved for your team.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['process', 'efficiency'],
    competencies: ['process_improvement', 'ownership'],
    timeLimitSec: 120,
  },
  {
    slug: 'team-conflict-resolution',
    prompt: 'Describe a time you helped resolve tension within a team.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 4,
    tags: ['conflict', 'teamwork'],
    competencies: ['collaboration', 'communication'],
    timeLimitSec: 150,
  },
  {
    slug: 'tradeoff-decision',
    prompt: 'Tell me about a tradeoff decision you made and why.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['tradeoffs', 'decision'],
    competencies: ['decision_making', 'judgment'],
    timeLimitSec: 120,
  },
  {
    slug: 'risk-management',
    prompt: 'Describe a time you identified and mitigated risk.',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 4,
    tags: ['risk', 'planning'],
    competencies: ['risk_management', 'planning'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-explain-api',
    prompt: 'Explain how you would design a simple REST API for a task manager.',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 2,
    tags: ['api', 'rest'],
    competencies: ['communication', 'system_thinking'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-debugging',
    prompt: 'Walk me through how you would debug a slow API endpoint.',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 3,
    tags: ['debugging', 'performance'],
    competencies: ['problem_solving', 'performance'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-scaling',
    prompt: 'Explain how you would scale a service that is hitting CPU limits.',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 4,
    tags: ['scaling', 'performance'],
    competencies: ['scalability', 'performance'],
    timeLimitSec: 180,
  },
  {
    slug: 'technical-caching',
    prompt: 'When would you add caching, and what would you cache first?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 3,
    tags: ['caching', 'performance'],
    competencies: ['system_thinking', 'performance'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-database-choice',
    prompt: 'How do you decide between SQL and NoSQL for a new feature?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 3,
    tags: ['database', 'tradeoffs'],
    competencies: ['decision_making', 'data_modeling'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-consistency',
    prompt: 'Explain eventual consistency to a non-technical stakeholder.',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 3,
    tags: ['consistency', 'communication'],
    competencies: ['communication', 'system_thinking'],
    timeLimitSec: 120,
  },
  {
    slug: 'technical-rate-limit',
    prompt: 'Describe how you would implement rate limiting for an API.',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 4,
    tags: ['rate_limit', 'api'],
    competencies: ['system_design', 'security'],
    timeLimitSec: 180,
  },
  {
    slug: 'technical-queue',
    prompt: 'When would you use a queue vs. a direct synchronous call?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 3,
    tags: ['queue', 'async'],
    competencies: ['system_thinking', 'reliability'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-monitoring',
    prompt: 'What metrics and alerts would you add to monitor a new service?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 3,
    tags: ['monitoring', 'observability'],
    competencies: ['reliability', 'operations'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-design-tradeoff',
    prompt: 'Describe a design tradeoff between latency and cost.',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 4,
    tags: ['tradeoffs', 'cost'],
    competencies: ['decision_making', 'performance'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-memory',
    prompt: 'How would you reduce memory usage in a backend service?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 4,
    tags: ['performance', 'memory'],
    competencies: ['performance', 'problem_solving'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-testing',
    prompt: 'How do you decide what to test for a new feature?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 2,
    tags: ['testing', 'quality'],
    competencies: ['quality', 'planning'],
    timeLimitSec: 120,
  },
  {
    slug: 'technical-logging',
    prompt: 'What makes logs useful during an incident?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 2,
    tags: ['logging', 'observability'],
    competencies: ['operations', 'problem_solving'],
    timeLimitSec: 120,
  },
  {
    slug: 'technical-dependency',
    prompt: 'How do you evaluate adding a new dependency to a project?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 2,
    tags: ['dependencies', 'risk'],
    competencies: ['decision_making', 'risk_management'],
    timeLimitSec: 120,
  },
  {
    slug: 'technical-bug-triage',
    prompt: 'Describe how you would triage a production bug with limited time.',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 4,
    tags: ['incident', 'triage'],
    competencies: ['problem_solving', 'operations'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-feature-rollout',
    prompt: 'How would you roll out a risky feature safely?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 3,
    tags: ['rollout', 'risk'],
    competencies: ['reliability', 'planning'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-auth',
    prompt: 'Explain how you would design authentication for a web app.',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 3,
    tags: ['auth', 'security'],
    competencies: ['security', 'system_thinking'],
    timeLimitSec: 150,
  },
  {
    slug: 'technical-privacy',
    prompt: 'How would you design a system to delete user data on request?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 4,
    tags: ['privacy', 'data'],
    competencies: ['privacy', 'system_design'],
    timeLimitSec: 180,
  },
  {
    slug: 'technical-tradeoff-availability',
    prompt: 'Describe how you would improve availability without a large budget.',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 4,
    tags: ['availability', 'cost'],
    competencies: ['reliability', 'tradeoffs'],
    timeLimitSec: 180,
  },
  {
    slug: 'technical-migration',
    prompt: 'How would you plan a data migration with minimal downtime?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 4,
    tags: ['migration', 'data'],
    competencies: ['planning', 'reliability'],
    timeLimitSec: 180,
  },
  {
    slug: 'technical-api-versioning',
    prompt: 'How do you handle API versioning without breaking clients?',
    mode: 'technical',
    pack: 'core_technical',
    difficulty: 3,
    tags: ['api', 'versioning'],
    competencies: ['communication', 'system_thinking'],
    timeLimitSec: 150,
  },
  {
    slug: 'system-design-url-shortener',
    prompt: 'Design a URL shortener.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 3,
    tags: ['url_shortener', 'storage'],
    competencies: ['system_design', 'scalability'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-notifications',
    prompt: 'Design a notification service that supports email and push.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['notifications', 'queue'],
    competencies: ['system_design', 'reliability'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-chat',
    prompt: 'Design a real-time chat system.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['chat', 'realtime'],
    competencies: ['system_design', 'scalability'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-feed',
    prompt: 'Design a social media news feed.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 5,
    tags: ['feed', 'ranking'],
    competencies: ['system_design', 'data_modeling'],
    timeLimitSec: 210,
  },
  {
    slug: 'system-design-search',
    prompt: 'Design a search suggestion service.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['search', 'autocomplete'],
    competencies: ['system_design', 'performance'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-analytics',
    prompt: 'Design an event analytics pipeline for product usage.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['analytics', 'pipeline'],
    competencies: ['data_systems', 'system_design'],
    timeLimitSec: 210,
  },
  {
    slug: 'system-design-file-storage',
    prompt: 'Design a file storage and sharing service.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['storage', 'files'],
    competencies: ['system_design', 'reliability'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-metrics',
    prompt: 'Design a metrics collection and alerting platform.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 5,
    tags: ['metrics', 'observability'],
    competencies: ['system_design', 'reliability'],
    timeLimitSec: 210,
  },
  {
    slug: 'system-design-payment',
    prompt: 'Design a payment processing system.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 5,
    tags: ['payments', 'security'],
    competencies: ['system_design', 'security'],
    timeLimitSec: 210,
  },
  {
    slug: 'system-design-rate-limiter',
    prompt: 'Design a distributed rate limiter.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['rate_limit', 'distributed'],
    competencies: ['system_design', 'scalability'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-video',
    prompt: 'Design a video streaming service.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 5,
    tags: ['video', 'cdn'],
    competencies: ['system_design', 'performance'],
    timeLimitSec: 210,
  },
  {
    slug: 'system-design-ride-sharing',
    prompt: 'Design a ride-sharing dispatch system.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 5,
    tags: ['geo', 'dispatch'],
    competencies: ['system_design', 'scalability'],
    timeLimitSec: 210,
  },
  {
    slug: 'system-design-time-series',
    prompt: 'Design a time-series database for IoT sensors.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 5,
    tags: ['time-series', 'data'],
    competencies: ['data_systems', 'system_design'],
    timeLimitSec: 210,
  },
  {
    slug: 'system-design-logs',
    prompt: 'Design a log aggregation service.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['logs', 'observability'],
    competencies: ['system_design', 'reliability'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-calendar',
    prompt: 'Design a shared calendar system.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['calendar', 'collaboration'],
    competencies: ['system_design', 'data_modeling'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-ab-testing',
    prompt: 'Design an A/B testing platform.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['experimentation', 'analytics'],
    competencies: ['system_design', 'data_systems'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-recommendations',
    prompt: 'Design a recommendation service for an e-commerce app.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 5,
    tags: ['recommendations', 'ml'],
    competencies: ['system_design', 'data_systems'],
    timeLimitSec: 210,
  },
  {
    slug: 'system-design-collaboration',
    prompt: 'Design a collaborative document editor.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 5,
    tags: ['collaboration', 'realtime'],
    competencies: ['system_design', 'consistency'],
    timeLimitSec: 210,
  },
  {
    slug: 'system-design-feature-flags',
    prompt: 'Design a feature flag service.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 3,
    tags: ['feature_flags', 'rollout'],
    competencies: ['system_design', 'reliability'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-dedup',
    prompt: 'Design a system to deduplicate incoming events.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['dedup', 'streaming'],
    competencies: ['system_design', 'data_systems'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-backup',
    prompt: 'Design a backup and restore system for a database.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['backup', 'reliability'],
    competencies: ['reliability', 'system_design'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-messaging',
    prompt: 'Design a message queue service.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['queue', 'messaging'],
    competencies: ['system_design', 'scalability'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-auth',
    prompt: 'Design an authentication and session service.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['auth', 'security'],
    competencies: ['system_design', 'security'],
    timeLimitSec: 180,
  },
  {
    slug: 'system-design-ai-feedback',
    prompt: 'Design a system that scores interview answers at scale.',
    mode: 'system_design',
    pack: 'core_system_design',
    difficulty: 4,
    tags: ['ml', 'scoring'],
    competencies: ['system_design', 'ml_systems'],
    timeLimitSec: 180,
  },
  {
    slug: 'weakness',
    prompt: 'What is your greatest weakness?',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 2,
    tags: ['self-awareness', 'growth'],
    competencies: ['self-awareness', 'authenticity'],
    timeLimitSec: 120,
  },
  {
    slug: 'motivation',
    prompt: 'What motivates you to do your best work?',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 2,
    tags: ['motivation', 'culture'],
    competencies: ['self-awareness', 'drive'],
    timeLimitSec: 120,
  },
  {
    slug: 'why-this-company',
    prompt: 'Why do you want to work here?',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 2,
    tags: ['research', 'interest'],
    competencies: ['company_alignment', 'enthusiasm'],
    timeLimitSec: 120,
  },
  {
    slug: 'difficult-coworker',
    prompt: 'How do you handle a difficult coworker?',
    mode: 'behavioral',
    pack: 'core_behavioral',
    difficulty: 3,
    tags: ['conflict', 'relationships'],
    competencies: ['emotional_intelligence', 'conflict_resolution'],
    timeLimitSec: 120,
  },
];
